bt_executer_node:
  ros__parameters:
    bt_xml_file: example.xml
    plugins:
      - move_to_pose
      - move_to_joint
      - gripper_command
      - dice_identification
    bt_package: drims2_behavior_tree