motion_server_node:
  ros__parameters:
    move_group_name: "ur_robot"
    end_effector_name: "ur10e_tool0"
    base_link_name: "base_link"
    joint_names:
      - "shoulder_pan_joint"
      - "shoulder_lift_joint"
      - "elbow_joint"
      - "wrist_1_joint"
      - "wrist_2_joint"
      - "wrist_3_joint"
    
    cartesian_planner_config:
      planning_pipeline: "pilz_industrial_motion_planner"
      planner_id: "LIN"
      planning_time: 50.0
      max_velocity_scaling_factor: 0.05
      max_acceleration_scaling_factor: 0.05
